### ISSUE TITLE
Sample Backlog 1

### ISSUE THREAD

**Issue by WONSEOKJE** [WONSEOKJE/repo-setup-sample#1]
## Description

프로젝트 작업 전 수행되어야 할 issue(backlog)를 template을 활용하여 만들었습니다.

## Tasks

- [ ] 게시글 작성 시 파일 업로드 구현
- [ ] 게시글 조회 시 예외 처리 구현
- [ ] 홈 화면 확실하게 정하기

## References

- [google](https://www.google.com)

**Comment by WONSEOKJE** [comment]
ok
